### ISSUE TITLE
Improved logging for Hummingbot Gateway

### ISSUE THREAD

**Issue by dennisocana** [CoinAlpha/gateway-api#29]
As discussed during the planning meeting, we've been testing from source but when we use Docker unless we're using debug mode it's harder to look at the data and reproduce issues like HTTP status 500.

On the gateway side, we don't have the same level of logging as Hummingbot where we have a traceback. @sdgoh suggested this and has started looking into this enhancement. Created this story for tracking and to discuss a better logging between gateway and Hummingbot client.

**Comment by sdgoh** [comment]
I added the logger support to log all info, error, unhandled exceptions to local files. 

```
# capture any info type logging
logs/app.log

# capture any error type logging
logs/error.log

# capture any unhandled exceptions
logs/rejection.log
```

PR: https://github.com/CoinAlpha/gateway-api/pull/31

**Comment by sdgoh** [comment]
Re-opened to add daily log file rotation, log path base-on env variable and GMT time offset for logger.

**Comment by sdgoh** [comment]
Hummingbot PR for Gateway docker install script: https://github.com/CoinAlpha/gateway-api/pull/32
