### ISSUE TITLE
Gateway architecture review and update

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/gateway-api#34]
Gateway architecture review & update to support future protocols with possible trading logic migration and other optimization from Hummingbot client's strategy over to the Gateway. 

Additional discussions and requirements will be updated after meeting with the engineering team.

**Comment by dennisocana** [comment]
The stories https://github.com/CoinAlpha/gateway-api/issues/36 and https://github.com/CoinAlpha/hummingbot/issues/2846 which are related to this have been completed.

Gateway documentation can be found here https://www.notion.so/hummingbot/Gateway-V2-9173d9e102a6436584969dce695f3906

Closing story for completion.
