### ISSUE TITLE
Refactor Gateway endpoint to consolidate functions

### ISSUE THREAD

**Issue by sdgoh** [CoinAlpha/gateway-api#36]
**Feature Suggestion**
Refactor Gateway endpoints to support multiple functions in a single API call.

The Ethereum-based protocol will reside under the `eth` endpoint.

```
/eth/balance
/eth/approve
/eth/poll
/eth/balancer/start
/eth/balancer/price
/eth/balancer/trade
/eth/{protocol}/{operations}
```

**Impact**
This will reduce the number of individual API calls from the Hummingbot client. 

**Additional context**
HB client connector/strategy requires an update in order to support the new endpoints.
https://github.com/CoinAlpha/hummingbot/issues/2846

**Comment by dennisocana** [comment]
Moved to v0.37 release
