### ISSUE TITLE
Perpetual protocol - could not detect network

### ISSUE THREAD

**Issue by RC-13** [CoinAlpha/gateway-api#45]
When using spot-perpetual strategy and perpetual protocol as derivatives exchange, doing balance check or starting strategy will result in failure to connect to the exchange. Upon checking the gateway side, we see that there is a network problem.
![perpfi-gateway](https://user-images.githubusercontent.com/57189990/110882451-e89f2980-831c-11eb-8a62-7038b7de3b9d.png)
Client side:
![perpfi1](https://user-images.githubusercontent.com/57189990/110882359-c3122000-831c-11eb-96e9-72378e3a14f8.png)

After a discussion with Victor, it appears that the issue is due to a faulty RPC provider, currently, https://dai.poa.network/ is used, we tried changing to a different provider https://rpc.xdaichain.com/ but still getting some problem such as opening and closing position.
[spot.zip](https://github.com/CoinAlpha/gateway-api/files/6127220/spot.zip)

**Comment by PtrckM** [comment]
to enter custom url provider: https://github.com/CoinAlpha/gateway-api/pull/37/commits/aec0f15c03b038e417a6cb0cd63cde4bd3f9c8d5

**Comment by mifeng** [comment]
Since Perpetual Protocol has moved from xDAI to Arbitrum, I think we should fix this issue in conjunction with adding this connector to v2 and changing to Arbitrum.
